"""Constants for the Mailcow integration."""
DOMAIN = "mailcow_ha_custom"
CONF_API_KEY = "api_key"
CONF_BASE_URL = "base_url"
IS_NOT_CHECK_START_HOUR = "is_not_check_start_hour"
IS_NOT_CHECK_END_HOUR = "is_not_check_end_hour"
